import { Inter, IBM_Plex_Sans } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";

const inter = Inter({ subsets: ["latin"] });
const ibm_plex_sans = IBM_Plex_Sans({
  subsets: ["latin"],
  weight: ['100', '200', '300', '400', '500', '600', '700'],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`min-h-screen ${ibm_plex_sans.className} text-[#141313] flex flex-row`}
      >
        <Sidebar />
        {children}
      </body>
    </html>
  );
}
